### PR TITLE
Merge in AIRR 2 AK LinkML export

### PR DESCRIPTION
**Pull request by bcorrie**

### CODE REVIEW

**Comment by bcorrie** [comment]
Closes https://github.com/airr-knowledge/issues/issues/28

**Comment by schristley** [comment]
@bcorrie I've started looking into this in more detail. For `Repertoire`, I see slots for the fields (like `repertoire_id`) and for the arrays (i.e. `sample`) but no slot for `Study` or `Subject`. I made a change to `airr2akc.py` that seems to add them but you should review as I'm guessing on what fields to set.

**Comment by bcorrie** [comment]
@schristley that should do the trick.

I should note that this code still needs a fair bit of refactoring, as it has many holdovers from the airr_flatten use case, which doesn't really apply to the use case here where we use it per AIRR object and never recurse on the Object REFs in the schema.

It could be simplified a fair bit, but I didn't want to invest that time until we were sure we wanted to have this capability...

**Comment by schristley** [comment]
@bcorrie I committed some changes to the enum output including changing the ontology to be a dynamic enum. I'm starting with `Study` but it's complaining about `KeywordsStudy`, essentially an enum is not being created for `keywords_study` for `Study` even though it's a controlled vocabulary. I guess maybe because it is an array? I couldn't figure out what to change, can you take a look?

Note, I didn't commit changes to all of the AIRR output files, so you might need to run `make -f Makefile.AIRR Study` first. I'm only trying to include AIRR Study as a start.

**Comment by bcorrie** [comment]
@schristley I wonder how valuable it is to go down the path of making a translation of the AIRR standard to LinkML slots bullet proof and 100% complete. 

The Enums for example:

- The fact that the AIRR standard has `keywords_study` might be totally irrelevant to the AKC - the AKC may never have such a field
- Even if we do have such a field in the AKC, it is unlikely that actual AKC Enum will be the same as the AIRR Enum

So having a LinkML Enum object for the AIRR field keywords_study may not be all that helpful. 

The big challenge for me is in the akc_convert.py code.

It is likely that this code would take as input a study in AIRR JSON format with the field 'keywords_study' populated and would convert that data to the appropriate AKC keyword if such a thing existed. 

So from a data integration perspective, we need to first decide if such a thing in the AKC exists and is so what the AKC Enum fields should be. If we have the field and the Enum is identical, then we can re-use the AIRR definition. If not we have to come up with some way to transform an AIRR `keywords_study` array to whatever the AKC expects.

The akc_convert.py code is also where the relationships between AIRR objects and the related AKC objects will be built. So it is perhaps more critical?

That is why the airr2akc code is "rather crude" at the moment. I wasn't sure how much effort we should put into it so I got the basics working and stopped... 8-)

**Comment by schristley** [comment]
> @schristley I wonder how valuable it is to go down the path of making a translation of the AIRR standard to LinkML slots bullet proof and 100% complete.

I'm still prototyping but I'm thinking about this as a way to manage schema versions and changes over time.

One challenge with the AIRR standards, and its python library, is that it only supports one schema version at a time. So the idea of having a program which can load two schemas, and manage the transition from one version to another, is not really possible with the library.

LinkML doesn't support namespaces at the moment, where we can have separate schema versions, but they are [talking](https://github.com/orgs/linkml/discussions/1739) about it.

**Comment by bcorrie** [comment]
If we think we want to further develop this, I might take the time to re-factor the code. It has too much of the old airr-flatten behaviour that isn't used in the LinkML conversion. That will make the code much cleaner and easier to understand...

**Comment by bcorrie** [comment]
> One challenge with the AIRR standards, and its python library, is that it only supports one schema version at a time. So the idea of having a program which can load two schemas, and manage the transition from one version to another, is not really possible with the library.

One fundamental question I wrestle with - do we want something that transitions a schema from one version to another or do we want something that transitions data from one schema version to another schema version. 

Maybe we want both?

1. With airr2akc.py, we can generate a LinkML schema based on different versions of the AIRR schema just by changing the docker container to use a different AIRR python module.
2. With akc-convert.py, we can translate data stored in different AIRR schema versions into data stored in the AKC schema by changing the  docker container to use a different AIRR python module and by using a different AIRR mapping file.

I am pretty sure we need #2, but if we have #2, do we need #1? 

I don't think we need something that translates data between AIRR v1.5 to AIRR v2.0 if we can go from AIRRv1.5 -> AKC and from AIRRv2.0 -> AKC.

**Comment by schristley** [comment]
> Maybe we want both?

I would like both, but we may not actually need both. I want to prototype ideas where that (data) mapping file is generated/updated by a program instead of manually by a human. I think it is valid to say, for AIRR v1.5 to v2.0, that's a much harder task than if we (as AIRR experts) just modify the mapping file ourselves. This puts it more in the research realm vs the practical task of getting it done. It may turn out to be a bust but I don't want to cut off the avenues to early in the project.

I'm also thinking about Aim 2.6 where we make a few promises:

- As new data is entered in the repositories, it needs to be propagated to the knowledgebase. We will develop rules and procedures for managing and periodically propagating this new data. Invariably, a human makes the final decision, but scripts and tools automate the workflows efficiency, consistency, and cohesiveness.
- For scientific reproducibility, we will devise a versioning strategy, specific to each DE and repository, that maintains historical content and provenance. We will utilize the PROV W3C standard for process description, customized with standardized attributes for each DE and repository, and will be auto-generated by the algorithms of Aims 2.2-2.4.

We've left ourselves plenty of wiggle room so that however the implementation turns out, we can accomplish the aim. Though we can explore some interesting automation ideas in the process.

Translating to AKC data model might not be the end point. Take for example if we want to run some analysis algorithms, we might need to put AKC data back into AIRR JSON and TSV format to run a tool. Also, if the schema changes, that spreads out to more than just the data import, as validation rules may change, APIs may change, parameters may change, etc.

Even something "simple" like, oh this field has changed, here are all the different places/programs where that field is being used, could provide a lot of value for understanding the scope of such a change.

**Comment by bcorrie** [comment]
@schristley can we merge this in to main as a basic first implementation. That way we don't have to worry about main diverging and merge conflicts down the road. 

I think what we have now is a decent base line. We can create new branches for refactoring etc.

**Comment by schristley** [comment]
> @schristley can we merge this in to main as a basic first implementation. That way we don't have to worry about main diverging and merge conflicts down the road.
> 
> I think what we have now is a decent base line. We can create new branches for refactoring etc.

@bcorrie Yes, I was having the similar thought.

**Comment by schristley** [comment]
@bcorrie I commented out AIRR for now, the Study object has some undefined enums.

The documentation build failure is the same error as on main, it seems to be an issue with some 3rd party package that isn't related to any of our changes, but I'll need to look further.

I need to manually handle the conflicts with main before merging.

**Pull request merged**
