### PR TITLE
Additions for Participant class.

### PR DESCRIPTION
**Pull request by bcorrie**
Added range values that currently exist in the ADC. Still remains to "consolidate" these to common terms.

Closes https://github.com/airr-knowledge/issues/issues/24

### CODE REVIEW

**Comment by schristley** [comment]
What about some of the fields in AIRR's Subject? Age, linked subjects, diagnoses, genotype?

**Comment by bcorrie** [comment]
> What about some of the fields in AIRR's Subject? Age, linked subjects, diagnoses, genotype?

I think diagnosis is part of the assessment/immune exposure/life event world no?
We have other entities for Genotype in the Consolidated doc so I assume that is not part of participant.

I have added age and linked_participant (although we have not discussed whether the last one is required).

**Comment by bcorrie** [comment]
I actually left out linked_participant because that feels to me like it should be a relationship that should be generalized? Maybe up for discussion.

**Review by schristley — APPROVED** [review]

**Comment by schristley** [comment]
> I actually left out linked_participant because that feels to me like it should be a relationship that should be generalized? Maybe up for discussion.

I've added to schema KG agenda.

**Pull request merged**
