### PR TITLE
Add Chain and Receptor

### PR DESCRIPTION
**Pull request by bcorrie**
Closes https://github.com/airr-knowledge/issues/issues/59

### CODE REVIEW

**Comment by bcorrie** [comment]
I am not sure why the build checks are failing?

**Comment by schristley** [comment]
> I am not sure why the build checks are failing?

It doesn't like the `text` property in the enum. I don't think they are needed.

**Comment by bcorrie** [comment]
> It doesn't like the `text` property in the enum. I don't think they are needed.

I [removed the enum text field](https://github.com/airr-knowledge/ak-schema/pull/6) from the generation of the AKC entities from the AIRR Standard as well...

**Comment by schristley** [comment]
I was thinking about making `ChainType` be ontology-based against the IMGT ontology but the integration of it into BioPortal is horrible. ChainType ends up having an id like `conceptid=http%3A%2F%2Fwww.imgt.org%2Fdownload%2FIMGT-ONTOLOGY%2FIMGT-ONTOLOGY-v1-0-3.owl%23ChainType`

**Comment by schristley** [comment]
@bcorrie ok, I think this is a pretty good start.

**Review by schristley — APPROVED** [review]

**Pull request merged**
